"""initial schema

Revision ID: 2d84a25288a5
Revises: 
Create Date: 2026-02-17 21:27:01.549596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d84a25288a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('final_capital', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('avg_win', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_loss', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_trade_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_wins', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_results_created_at'), 'backtest_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_results_run_id'), 'backtest_results', ['run_id'], unique=True)
    op.create_index(op.f('ix_backtest_results_strategy'), 'backtest_results', ['strategy'], unique=False)
    op.create_index('ix_backtest_results_strategy_created', 'backtest_results', ['strategy', 'created_at'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'open_time', name='uq_candle')
    )
    op.create_index(op.f('ix_candles_open_time'), 'candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index('ix_candles_symbol_timeframe_time', 'candles', ['symbol', 'timeframe', 'open_time'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_table('order_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('slippage_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fee_usdt', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_records_created_at'), 'order_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_records_status'), 'order_records', ['status'], unique=False)
    op.create_index('ix_order_records_status_created', 'order_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_order_records_symbol'), 'order_records', ['symbol'], unique=False)
    op.create_index('ix_order_records_symbol_created', 'order_records', ['symbol', 'created_at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usdt_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('highest_close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('trailing_stop_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('hard_stop_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('scale_in_count', sa.Integer(), nullable=False),
    sa.Column('buy_signal_candles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index('ix_positions_symbol_strategy', 'positions', ['symbol', 'strategy'], unique=False)
    op.create_table('strategy_state',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_buy_candles', sa.Integer(), nullable=False),
    sa.Column('last_exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'strategy', name='uq_strategy_state')
    )
    op.create_index(op.f('ix_strategy_state_strategy'), 'strategy_state', ['strategy'], unique=False)
    op.create_index(op.f('ix_strategy_state_symbol'), 'strategy_state', ['symbol'], unique=False)
    op.create_table('trade_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pnl_usdt', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pnl_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=False),
    sa.Column('max_favorable_excursion', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_records_entry_time'), 'trade_records', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trade_records_exit_time'), 'trade_records', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trade_records_strategy'), 'trade_records', ['strategy'], unique=False)
    op.create_index('ix_trade_records_strategy_exit', 'trade_records', ['strategy', 'exit_time'], unique=False)
    op.create_index(op.f('ix_trade_records_symbol'), 'trade_records', ['symbol'], unique=False)
    op.create_index('ix_trade_records_symbol_strategy_entry', 'trade_records', ['symbol', 'strategy', 'entry_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_records_symbol_strategy_entry', table_name='trade_records')
    op.drop_index(op.f('ix_trade_records_symbol'), table_name='trade_records')
    op.drop_index('ix_trade_records_strategy_exit', table_name='trade_records')
    op.drop_index(op.f('ix_trade_records_strategy'), table_name='trade_records')
    op.drop_index(op.f('ix_trade_records_exit_time'), table_name='trade_records')
    op.drop_index(op.f('ix_trade_records_entry_time'), table_name='trade_records')
    op.drop_table('trade_records')
    op.drop_index(op.f('ix_strategy_state_symbol'), table_name='strategy_state')
    op.drop_index(op.f('ix_strategy_state_strategy'), table_name='strategy_state')
    op.drop_table('strategy_state')
    op.drop_index('ix_positions_symbol_strategy', table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_order_records_symbol_created', table_name='order_records')
    op.drop_index(op.f('ix_order_records_symbol'), table_name='order_records')
    op.drop_index('ix_order_records_status_created', table_name='order_records')
    op.drop_index(op.f('ix_order_records_status'), table_name='order_records')
    op.drop_index(op.f('ix_order_records_created_at'), table_name='order_records')
    op.drop_table('order_records')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index('ix_candles_symbol_timeframe_time', table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_open_time'), table_name='candles')
    op.drop_table('candles')
    op.drop_index('ix_backtest_results_strategy_created', table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_strategy'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_run_id'), table_name='backtest_results')
    op.drop_index(op.f('ix_backtest_results_created_at'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
