"""add order reconciliation columns

Revision ID: 60c1d49f6519
Revises: b3619ed60e1e
Create Date: 2026-05-05 12:09:49.143090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c1d49f6519'
down_revision: Union[str, Sequence[str], None] = 'b3619ed60e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_records', sa.Column('intent', sa.String(length=20), nullable=True))
    op.add_column('order_records', sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('order_records', sa.Column('reconciliation_status', sa.String(length=20), server_default='pending_sync', nullable=False))
    op.create_index('ix_order_records_exchange_order_id', 'order_records', ['exchange_order_id'], unique=False)
    op.create_index('ix_order_records_reconciliation', 'order_records', ['reconciliation_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_records_reconciliation', table_name='order_records')
    op.drop_index('ix_order_records_exchange_order_id', table_name='order_records')
    op.drop_column('order_records', 'reconciliation_status')
    op.drop_column('order_records', 'reconciled_at')
    op.drop_column('order_records', 'intent')
    # ### end Alembic commands ###
