"""add lowest_close to positions

Revision ID: b3619ed60e1e
Revises: k6l7m8n9o012
Create Date: 2026-05-04 16:12:04.796508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3619ed60e1e'
down_revision: Union[str, Sequence[str], None] = 'k6l7m8n9o012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('lowest_close', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'lowest_close')
    # ### end Alembic commands ###
