"""add stop_price to order_records

Revision ID: f0d5aac698ea
Revises: a1b2c3d4e504
Create Date: 2026-05-06 20:26:32.823109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d5aac698ea'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_records', sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_records', 'stop_price')
    # ### end Alembic commands ###
