"""add unique constraint exchange_order_id trading_mode

Revision ID: fb2f54f41350
Revises: f0d5aac698ea
Create Date: 2026-05-06 20:31:52.576986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2f54f41350'
down_revision: Union[str, Sequence[str], None] = 'f0d5aac698ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_order_exchange_id_mode', 'order_records', ['exchange_order_id', 'trading_mode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_exchange_id_mode', 'order_records', type_='unique')
    # ### end Alembic commands ###
