// ── Trading Enums ────────────────────────────────────────────────────────────
// String literal unions matching Python `str, Enum` definitions in core/models.py

/** Trading signals generated by strategies. */
export type Signal = 'buy' | 'sell_full' | 'sell_half' | 'hold';

/** State machine states for strategies. */
export type StrategyState = 'flat' | 'position' | 'reduced' | 'cooldown';

/** Order side. */
export type OrderSide = 'buy' | 'sell';

/** Order types. */
export type OrderType = 'market' | 'limit';

/** Order status lifecycle. */
export type OrderStatus = 'pending' | 'filled' | 'partial' | 'rejected' | 'cancelled';

/** Reasons for trade exit. */
export type ExitReason =
  | 'ema_cross'
  | 'close_below_ema200'
  | 'momentum_fade'
  | 'trailing_stop'
  | 'hard_stop'
  | 'manual'
  | 'time_stop'
  | 'middle_bb';

/** Actions authorised by the risk engine. */
export type RiskAction = 'open' | 'scale_in' | 'reduce' | 'close' | 'hold';

// ── Event Enums ─────────────────────────────────────────────────────────────
// Matching definitions in core/events.py

/** Redis pub/sub channels (prefixed with `gg:`). */
export type EventChannel =
  | 'gg:market_data'
  | 'gg:strategy'
  | 'gg:risk'
  | 'gg:execution'
  | 'gg:portfolio'
  | 'gg:system';

/** All event types the platform can emit. */
export type EventType =
  // Market Data
  | 'candle_received'
  | 'indicators_computed'
  | 'price_update'
  // Strategy
  | 'signal_generated'
  | 'state_changed'
  | 'conditions_evaluated'
  // Risk
  | 'risk_evaluated'
  | 'stop_triggered'
  | 'position_sized'
  // Execution
  | 'order_created'
  | 'order_filled'
  | 'order_rejected'
  | 'order_cancelled'
  // Portfolio
  | 'position_opened'
  | 'position_updated'
  | 'trade_closed'
  | 'balance_updated'
  | 'equity_updated'
  // System
  | 'heartbeat'
  | 'error'
  | 'warning'
  | 'startup'
  | 'shutdown';
