"""
Pydantic models for business logic and data validation.

These models represent data structures used throughout the application.
They are separate from database ORM models to maintain clean separation
between business logic and persistence layers.
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ── Enums ────────────────────────────────────────────────────────────────────

class Signal(str, Enum):
    """Trading signals generated by strategies."""
    BUY = "buy"
    SELL_FULL = "sell_full"  # Exit 100% of position
    SELL_HALF = "sell_half"  # Exit 50% of position (momentum fade)
    HOLD = "hold"


class StrategyState(str, Enum):
    """State machine states for Smart Hodler strategy."""
    FLAT = "flat"           # No position
    POSITION = "position"   # Holding position, can scale in
    REDUCED = "reduced"     # Partial position after momentum fade exit
    COOLDOWN = "cooldown"   # Waiting period after exit/stop


class OrderSide(str, Enum):
    """Order side (buy or sell)."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order types."""
    MARKET = "market"
    LIMIT = "limit"


class OrderStatus(str, Enum):
    """Order status lifecycle."""
    PENDING = "pending"
    FILLED = "filled"
    PARTIAL = "partial"
    REJECTED = "rejected"
    CANCELLED = "cancelled"


class ExitReason(str, Enum):
    """Reasons for trade exit."""
    EMA_CROSS = "ema_cross"                    # EMA50 < EMA200
    CLOSE_BELOW_EMA200 = "close_below_ema200"  # 2 consecutive candles
    MOMENTUM_FADE = "momentum_fade"            # ADX falling, partial exit
    TRAILING_STOP = "trailing_stop"            # Hit trailing stop
    HARD_STOP = "hard_stop"                    # Hit 3% max drawdown
    MANUAL = "manual"                          # Manual intervention


# ── Core Data Models ─────────────────────────────────────────────────────────

class Candle(BaseModel):
    """
    Single candle (OHLCV) data.
    
    Represents a single time period of market data.
    """
    open_time: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal
    quote_volume: Optional[Decimal] = None
    trades_count: Optional[int] = None
    
    @field_validator("open", "high", "low", "close", "volume", mode="before")
    @classmethod
    def ensure_positive(cls, v: Any) -> Decimal:
        """Ensure price and volume values are positive."""
        if v is not None:
            value = Decimal(str(v))
            if value < 0:
                raise ValueError("Price and volume must be positive")
            return value
        return v
    
    @model_validator(mode='after')
    def validate_high_low(self) -> 'Candle':
        """Validate that high is >= low."""
        if self.high < self.low:
            raise ValueError("High must be >= low")
        return self
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class MarketData(BaseModel):
    """
    Normalized market data passed through the system.
    
    Contains candles and calculated indicators for a specific symbol and timeframe.
    """
    symbol: str
    timeframe: str
    candles: pd.DataFrame  # Columns: open_time, open, high, low, close, volume
    indicators: Dict[str, pd.Series] = Field(default_factory=dict)
    
    @field_validator("symbol")
    @classmethod
    def validate_symbol(cls, v: str) -> str:
        """Validate symbol format."""
        if not v or not v.isupper():
            raise ValueError("Symbol must be uppercase")
        return v
    
    @field_validator("timeframe")
    @classmethod
    def validate_timeframe(cls, v: str) -> str:
        """Validate timeframe format."""
        valid = {"1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"}
        if v not in valid:
            raise ValueError(f"Invalid timeframe: {v}. Must be one of {valid}")
        return v
    
    model_config = ConfigDict(arbitrary_types_allowed=True)  # Allow pandas DataFrame


class Position(BaseModel):
    """
    Open position data.
    
    Tracks an active long position with entry price, stops, and scaling info.
    """
    symbol: str
    size: Decimal  # Amount in base asset (e.g., BTC)
    entry_price: Decimal  # Average entry price
    entry_time: datetime
    highest_close: Decimal  # For trailing stop calculation
    trailing_stop_price: Decimal
    hard_stop_price: Decimal  # -3% from entry
    scale_in_count: int = 0  # 0, 1, 2 for 50%, 75%, 100%
    buy_signal_candles: int = 0  # Consecutive candles with BUY signal
    unrealized_pnl: Optional[Decimal] = None
    unrealized_pnl_percent: Optional[Decimal] = None
    
    @field_validator("scale_in_count")
    @classmethod
    def validate_scale_in_count(cls, v: int) -> int:
        """Scale-in count must be 0, 1, or 2."""
        if v not in {0, 1, 2}:
            raise ValueError("scale_in_count must be 0, 1, or 2")
        return v
    
    def calculate_unrealized_pnl(self, current_price: Decimal) -> tuple[Decimal, Decimal]:
        """
        Calculate unrealized PnL.
        
        Args:
            current_price: Current market price
        
        Returns:
            tuple: (pnl_usdt, pnl_percent)
        """
        pnl_per_unit = current_price - self.entry_price
        pnl_usdt = pnl_per_unit * self.size
        pnl_percent = (current_price / self.entry_price - 1) * 100
        return pnl_usdt, pnl_percent
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Trade(BaseModel):
    """
    Closed trade record.
    
    Represents a completed trade with entry/exit details and PnL.
    """
    symbol: str
    strategy: str = "smart_hodler"
    entry_price: Decimal
    exit_price: Decimal
    size: Decimal
    entry_time: datetime
    exit_time: datetime
    pnl_usdt: Decimal
    pnl_percent: Decimal
    duration_minutes: int
    exit_reason: ExitReason
    max_favorable_excursion: Optional[Decimal] = None  # MFE
    max_adverse_excursion: Optional[Decimal] = None    # MAE
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Order(BaseModel):
    """
    Order record.
    
    Represents a buy or sell order with execution details.
    """
    symbol: str
    side: OrderSide
    order_type: OrderType
    amount: Decimal
    price: Optional[Decimal] = None  # None for market orders
    status: OrderStatus = OrderStatus.PENDING
    filled_amount: Decimal = Decimal("0")
    avg_fill_price: Optional[Decimal] = None
    slippage_percent: Optional[Decimal] = None
    fee_usdt: Optional[Decimal] = None
    exchange_order_id: Optional[str] = None  # Binance order ID
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Portfolio(BaseModel):
    """
    Portfolio state.
    
    Tracks USDT balance, open positions, and equity.
    """
    usdt_balance: Decimal
    positions: Dict[str, Position] = Field(default_factory=dict)  # symbol -> Position
    equity: Decimal  # Total equity (balance + positions value)
    total_pnl: Decimal = Decimal("0")
    open_trades_count: int = 0
    
    @property
    def available_capital(self) -> Decimal:
        """Calculate available capital for new positions."""
        return self.usdt_balance
    
    @property
    def positions_value(self) -> Decimal:
        """Calculate total value of open positions."""
        return sum(
            pos.size * pos.entry_price
            for pos in self.positions.values()
        )
    
    def update_equity(self, current_prices: Dict[str, Decimal]) -> None:
        """
        Update equity based on current market prices.
        
        Args:
            current_prices: Dict of symbol -> current price
        """
        positions_market_value = Decimal("0")
        for symbol, position in self.positions.items():
            if symbol in current_prices:
                positions_market_value += position.size * current_prices[symbol]
        
        self.equity = self.usdt_balance + positions_market_value
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
        }
    )


class StrategyConditions(BaseModel):
    """
    Conditions checklist for Smart Hodler strategy.
    
    Used for debugging and UI display to show which conditions are met.
    """
    ema_cross_bullish: bool = False
    adx_above_threshold: bool = False
    close_above_ema_fast: bool = False
    volume_above_average: bool = False
    hourly_ema_rising: bool = False
    hourly_rsi_above_threshold: bool = False
    session_filter_pass: bool = False
    
    @property
    def all_buy_conditions_met(self) -> bool:
        """Check if all BUY conditions are satisfied."""
        return all([
            self.ema_cross_bullish,
            self.adx_above_threshold,
            self.close_above_ema_fast,
            self.volume_above_average,
            self.hourly_ema_rising,
            self.hourly_rsi_above_threshold,
            self.session_filter_pass,
        ])


class BacktestMetrics(BaseModel):
    """
    Backtest results and metrics.
    
    Comprehensive statistics for strategy performance evaluation.
    """
    run_id: str
    strategy: str
    symbol: str
    start_date: datetime
    end_date: datetime
    initial_capital: Decimal
    final_capital: Decimal
    total_return: Decimal  # Percentage
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: Decimal  # Percentage
    avg_win: Decimal
    avg_loss: Decimal
    max_drawdown: Decimal  # Percentage
    sharpe_ratio: Optional[Decimal] = None
    profit_factor: Optional[Decimal] = None  # Gross profit / Gross loss
    avg_trade_duration_minutes: Optional[int] = None
    max_consecutive_wins: Optional[int] = None
    max_consecutive_losses: Optional[int] = None
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class PortfolioSnapshot(BaseModel):
    """
    Point-in-time portfolio snapshot for equity curve.
    
    Used to track portfolio performance over time.
    """
    timestamp: datetime
    usdt_balance: Decimal
    positions_value: Decimal
    total_equity: Decimal
    daily_pnl: Optional[Decimal] = None
    total_pnl: Decimal = Decimal("0")
    open_positions_count: int = 0
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


# ── Exports ──────────────────────────────────────────────────────────────────

__all__ = [
    "Signal",
    "StrategyState",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "ExitReason",
    "Candle",
    "MarketData",
    "Position",
    "Trade",
    "Order",
    "Portfolio",
    "StrategyConditions",
    "BacktestMetrics",
    "PortfolioSnapshot",
]
