"""
Pydantic models for business logic and data validation.

These models represent data structures used throughout the application.
They are separate from database ORM models to maintain clean separation
between business logic and persistence layers.
"""

from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


# ── Enums ────────────────────────────────────────────────────────────────────

class Signal(str, Enum):
    """Trading signals generated by strategies."""
    BUY = "buy"
    SELL_FULL = "sell_full"  # Exit 100% of position
    SELL_HALF = "sell_half"  # Exit 50% of position (momentum fade)
    HOLD = "hold"
    SHORT = "short"          # Open short position (bear trend)


class PositionSide(str, Enum):
    """Side of a position (long or short)."""
    LONG = "long"
    SHORT = "short"


class StrategyState(str, Enum):
    """State machine states for Smart Hodler strategy."""
    FLAT = "flat"           # No position
    POSITION = "position"   # Holding position, can scale in
    REDUCED = "reduced"     # Partial position after momentum fade exit
    COOLDOWN = "cooldown"   # Waiting period after exit/stop


class OrderSide(str, Enum):
    """Order side (buy or sell)."""
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Order types."""
    MARKET = "market"
    LIMIT = "limit"
    STOP_LOSS_LIMIT = "stop_loss_limit"


class OrderStatus(str, Enum):
    """Order status lifecycle."""
    PENDING = "pending"
    FILLED = "filled"
    PARTIAL = "partial"
    REJECTED = "rejected"
    CANCELLED = "cancelled"


class TimeInForce(str, Enum):
    """Time-in-force policies for limit orders."""
    GTC = "GTC"  # Good 'Til Cancelled
    IOC = "IOC"  # Immediate Or Cancel
    FOK = "FOK"  # Fill Or Kill


class ExitReason(str, Enum):
    """Reasons for trade exit."""
    EMA_CROSS = "ema_cross"                    # EMA50 < EMA200
    CLOSE_BELOW_EMA200 = "close_below_ema200"  # 2 consecutive candles
    MOMENTUM_FADE = "momentum_fade"            # ADX falling, partial exit
    TRAILING_STOP = "trailing_stop"            # Hit trailing stop
    HARD_STOP = "hard_stop"                    # Hit 3% max drawdown
    MANUAL = "manual"                          # Manual intervention
    TIME_STOP = "time_stop"                    # Mean Reversion: 16-candle timeout
    MIDDLE_BB = "middle_bb"                    # Mean Reversion: partial exit at middle BB
    RECONCILIATION_FORCE_CLOSE = "reconciliation_force_close"  # Force-closed by reconciliation


class OrderIntent(str, Enum):
    """What the GG intended when placing an order — used for fill recovery."""
    OPEN_LONG = "open_long"
    CLOSE_LONG = "close_long"
    OPEN_SHORT = "open_short"
    CLOSE_SHORT = "close_short"
    STOP_LOSS = "stop_loss"
    SCALE_IN = "scale_in"
    REDUCE = "reduce"


class ReconciliationStatus(str, Enum):
    """Reconciliation state of an order record against the exchange."""
    PENDING_SYNC = "pending_sync"
    SYNCED = "synced"
    ORPHAN = "orphan"
    RECOVERED = "recovered"
    LOST = "lost"


class RiskAction(str, Enum):
    """Actions authorised by the risk engine."""
    OPEN = "open"          # Open a new position
    SCALE_IN = "scale_in"  # Add to existing position
    REDUCE = "reduce"      # Partial close
    CLOSE = "close"        # Full close
    HOLD = "hold"          # No action


class RiskDecision(BaseModel):
    """
    Output of the risk engine for a single evaluation tick.

    Translates a raw strategy Signal into a concrete, sized instruction
    that the executor can act on.
    """
    action: RiskAction
    symbol: str = ""
    side: PositionSide = PositionSide.LONG  # Position direction for executor
    size: Decimal = Decimal("0")           # Base-asset amount (e.g. BTC qty)
    price: Decimal = Decimal("0")          # Reference price (current close)
    exit_reason: Optional[ExitReason] = None
    sell_fraction: Optional[Decimal] = None
    hard_stop_price: Optional[Decimal] = None
    trailing_stop_price: Optional[Decimal] = None

    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
        }
    )


class StopCheckResult(BaseModel):
    """
    Return value of ``RiskEngine.check_stops()``.

    Carries both a potential exit decision *and* updated stop-level
    values so the caller can persist them via
    ``PortfolioManager.update_stops()``.

    When a hard stop fires, ``cooldown_candles`` signals how many
    candles the caller should block re-entry for this symbol.
    """
    decision: Optional[RiskDecision] = None
    highest_close: Optional[Decimal] = None
    lowest_close: Optional[Decimal] = None
    trailing_stop_price: Optional[Decimal] = None
    hard_stop_price: Optional[Decimal] = None
    cooldown_candles: Optional[int] = None

    @property
    def stop_hit(self) -> bool:
        """True when a stop triggered an exit."""
        return self.decision is not None and self.decision.action == RiskAction.CLOSE

    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
        }
    )


# ── Core Data Models ─────────────────────────────────────────────────────────

class Candle(BaseModel):
    """
    Single candle (OHLCV) data.
    
    Represents a single time period of market data.
    """
    open_time: datetime
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal
    quote_volume: Optional[Decimal] = None
    trades_count: Optional[int] = None
    
    @field_validator("open", "high", "low", "close", mode="before")
    @classmethod
    def ensure_positive_price(cls, v: Any) -> Decimal:
        """Ensure price values are strictly positive (no zero)."""
        if v is not None:
            value = Decimal(str(v))
            if value <= 0:
                raise ValueError("Price must be positive")
            return value
        return v

    @field_validator("volume", mode="before")
    @classmethod
    def ensure_non_negative_volume(cls, v: Any) -> Decimal:
        """Ensure volume is non-negative (zero is valid for low-liquidity candles)."""
        if v is not None:
            value = Decimal(str(v))
            if value < 0:
                raise ValueError("Volume must be non-negative")
            return value
        return v
    
    @model_validator(mode='after')
    def validate_high_low(self) -> 'Candle':
        """Validate that high is >= low."""
        if self.high < self.low:
            raise ValueError("High must be >= low")
        return self
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class MarketData(BaseModel):
    """
    Normalized market data passed through the system.
    
    Contains candles and calculated indicators for a specific symbol and timeframe.
    Optionally carries a secondary (confirmation) timeframe for multi-timeframe
    strategies (e.g., 15m primary + 1H confirmation).
    """
    # ── Primary timeframe (required) ─────────────────────────────────────
    symbol: str
    timeframe: str
    candles: pd.DataFrame  # Columns: open_time, open, high, low, close, volume
    indicators: Dict[str, pd.Series] = Field(default_factory=dict)

    # ── Secondary / confirmation timeframe (optional) ────────────────────
    secondary_timeframe: Optional[str] = None
    secondary_candles: Optional[pd.DataFrame] = None
    secondary_indicators: Dict[str, pd.Series] = Field(default_factory=dict)
    
    @field_validator("symbol")
    @classmethod
    def validate_symbol(cls, v: str) -> str:
        """Validate symbol format."""
        if not v or not v.isupper():
            raise ValueError("Symbol must be uppercase")
        return v
    
    @field_validator("timeframe")
    @classmethod
    def validate_timeframe(cls, v: str) -> str:
        """Validate timeframe format."""
        valid = {"1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"}
        if v not in valid:
            raise ValueError(f"Invalid timeframe: {v}. Must be one of {valid}")
        return v
    
    @field_validator("secondary_timeframe")
    @classmethod
    def validate_secondary_timeframe(cls, v: Optional[str]) -> Optional[str]:
        """Validate secondary timeframe format when provided."""
        if v is not None:
            valid = {"1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"}
            if v not in valid:
                raise ValueError(f"Invalid secondary timeframe: {v}. Must be one of {valid}")
        return v
    
    @model_validator(mode='after')
    def validate_secondary_fields(self) -> 'MarketData':
        """Ensure secondary_timeframe and secondary_candles are both set or both unset."""
        has_tf = self.secondary_timeframe is not None
        has_candles = self.secondary_candles is not None
        if has_tf != has_candles:
            raise ValueError(
                "secondary_timeframe and secondary_candles must both be set or both be None"
            )
        return self
    
    def get_indicator(self, name: str, timeframe: Optional[str] = None) -> pd.Series:
        """
        Get an indicator by name, optionally from a specific timeframe.
        
        Args:
            name: Indicator key (e.g. 'ema_50', 'rsi', 'adx').
            timeframe: Timeframe to read from. Defaults to primary.
                       Pass secondary_timeframe to read from confirmation data.
        
        Returns:
            pd.Series with the indicator values.
        
        Raises:
            KeyError: If the indicator or timeframe is not found.
        """
        if timeframe is None or timeframe == self.timeframe:
            if name not in self.indicators:
                raise KeyError(
                    f"Indicator '{name}' not found in primary ({self.timeframe}) indicators. "
                    f"Available: {list(self.indicators.keys())}"
                )
            return self.indicators[name]
        elif timeframe == self.secondary_timeframe:
            if name not in self.secondary_indicators:
                raise KeyError(
                    f"Indicator '{name}' not found in secondary ({self.secondary_timeframe}) indicators. "
                    f"Available: {list(self.secondary_indicators.keys())}"
                )
            return self.secondary_indicators[name]
        else:
            raise KeyError(
                f"Timeframe '{timeframe}' not available. "
                f"Primary: {self.timeframe}, Secondary: {self.secondary_timeframe}"
            )
    
    @property
    def has_secondary(self) -> bool:
        """Check if secondary timeframe data is available."""
        return self.secondary_timeframe is not None
    
    model_config = ConfigDict(arbitrary_types_allowed=True)  # Allow pandas DataFrame


class Position(BaseModel):
    """
    Open position data.
    
    Tracks an active position with entry price, stops, and scaling info.
    """
    symbol: str
    strategy: str = "unknown"  # Strategy that opened this position
    side: PositionSide = PositionSide.LONG  # Position direction
    size: Decimal  # Amount in base asset (e.g., BTC)
    entry_price: Decimal  # Average entry price
    entry_time: datetime
    highest_close: Decimal  # For trailing stop calculation (longs)
    lowest_close: Optional[Decimal] = None  # For trailing stop calculation (shorts)
    trailing_stop_price: Decimal
    hard_stop_price: Decimal  # -3% from entry (longs) / +5% from entry (shorts)
    scale_in_count: int = 0  # 0, 1, 2 for 50%, 75%, 100%
    buy_signal_candles: int = 0  # Consecutive candles with BUY signal
    exchange_stop_order_id: Optional[str] = None
    unrealized_pnl: Optional[Decimal] = None
    unrealized_pnl_percent: Optional[Decimal] = None
    
    @field_validator("scale_in_count")
    @classmethod
    def validate_scale_in_count(cls, v: int) -> int:
        """Scale-in count must be 0, 1, or 2."""
        if v not in {0, 1, 2}:
            raise ValueError("scale_in_count must be 0, 1, or 2")
        return v
    
    def calculate_unrealized_pnl(self, current_price: Decimal) -> tuple[Decimal, Decimal]:
        """
        Calculate unrealized PnL.
        
        Args:
            current_price: Current market price
        
        Returns:
            tuple: (pnl_usdt, pnl_percent)
        """
        if self.side == PositionSide.SHORT:
            pnl_per_unit = self.entry_price - current_price
            pnl_percent = (self.entry_price - current_price) / self.entry_price * 100
        else:
            pnl_per_unit = current_price - self.entry_price
            pnl_percent = (current_price / self.entry_price - 1) * 100
        pnl_usdt = pnl_per_unit * self.size
        return pnl_usdt, pnl_percent
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Trade(BaseModel):
    """
    Closed trade record.
    
    Represents a completed trade with entry/exit details and PnL.
    """
    symbol: str
    strategy: str  # required — must be supplied by the caller (e.g. "smart_hodler", "mean_reversion")
    entry_price: Decimal
    exit_price: Decimal
    size: Decimal
    entry_time: datetime
    exit_time: datetime
    pnl_usdt: Decimal
    pnl_percent: Decimal
    duration_minutes: int
    exit_reason: ExitReason
    max_favorable_excursion: Optional[Decimal] = None  # MFE
    max_adverse_excursion: Optional[Decimal] = None    # MAE
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Order(BaseModel):
    """
    Order record.
    
    Represents a buy or sell order with execution details.
    """
    run_id: Optional[str] = None
    symbol: str
    side: OrderSide
    order_type: OrderType
    amount: Decimal
    price: Optional[Decimal] = None  # None for market orders
    status: OrderStatus = OrderStatus.PENDING
    filled_amount: Decimal = Decimal("0")
    avg_fill_price: Optional[Decimal] = None
    slippage_percent: Optional[Decimal] = None
    fee_usdt: Optional[Decimal] = None
    exchange_order_id: Optional[str] = None  # Binance order ID
    time_in_force: Optional[TimeInForce] = None  # GTC/IOC/FOK for limit orders
    limit_price: Optional[Decimal] = None  # Explicit limit price (separate from fill price)
    reject_reason: Optional[str] = None  # Why the exchange rejected/cancelled
    exchange_status: Optional[str] = None  # Raw exchange status string for debugging
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class ExecutionResult(BaseModel):
    """
    Return value of ``Executor.execute()``.

    Bundles the filled Order with the resulting Position (buy-side)
    or Trade (sell-side) so the backtest runner has a single return
    value.
    """
    order: 'Order'
    position: Optional['Position'] = None   # set for OPEN / SCALE_IN
    trade: Optional['Trade'] = None         # set for REDUCE / CLOSE

    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class Portfolio(BaseModel):
    """
    Portfolio state.
    
    Tracks USDT balance, open positions, equity, trade history,
    and equity curve snapshots.
    """
    usdt_balance: Decimal
    positions: Dict[str, Position] = Field(default_factory=dict)  # symbol -> Position
    equity: Decimal  # Total equity (balance + positions value)
    total_pnl: Decimal = Decimal("0")
    open_trades_count: int = 0
    trade_history: List['Trade'] = Field(default_factory=list)
    equity_curve: List['PortfolioSnapshot'] = Field(default_factory=list)
    
    @property
    def available_capital(self) -> Decimal:
        """Calculate available capital for new positions."""
        return self.usdt_balance
    
    @property
    def positions_cost_basis(self) -> Decimal:
        """Total cost basis of open positions (entry_price × size).

        This is NOT mark-to-market. Use ``equity`` (updated by
        ``update_equity()``) for the current market value.
        """
        return sum(
            pos.size * pos.entry_price
            for pos in self.positions.values()
        )
    
    def update_equity(self, current_prices: Dict[str, Decimal]) -> None:
        """
        Update equity based on current market prices.
        
        Args:
            current_prices: Dict of symbol -> current price
        """
        positions_market_value = Decimal("0")
        for symbol, position in self.positions.items():
            if symbol in current_prices:
                positions_market_value += position.size * current_prices[symbol]
        
        self.equity = self.usdt_balance + positions_market_value
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
        }
    )


class StrategyConditions(BaseModel):
    """
    Conditions checklist for Smart Hodler strategy.
    
    Used for debugging and UI display to show which conditions are met.
    """
    ema_cross_bullish: bool = False
    adx_above_threshold: bool = False
    close_above_ema_fast: bool = False
    volume_above_average: bool = False
    hourly_ema_rising: bool = False
    hourly_rsi_above_threshold: bool = False
    session_filter_pass: bool = False
    
    @property
    def all_buy_conditions_met(self) -> bool:
        """Check if all BUY conditions are satisfied."""
        return all([
            self.ema_cross_bullish,
            self.adx_above_threshold,
            self.close_above_ema_fast,
            self.volume_above_average,
            self.hourly_ema_rising,
            self.hourly_rsi_above_threshold,
            self.session_filter_pass,
        ])


class MeanReversionConditions(BaseModel):
    """
    Conditions checklist for Mean Reversion strategy.

    Used for debugging and UI display to show which conditions are met.
    The BUY gate requires all seven conditions simultaneously.
    """
    close_below_lower_bb: bool = False
    rsi_oversold: bool = False
    adx_below_threshold: bool = False
    volume_spike: bool = False
    hourly_rsi_ok: bool = False
    hourly_close_above_ema: bool = False
    session_filter_pass: bool = False

    @property
    def all_buy_conditions_met(self) -> bool:
        """Check if all BUY conditions are satisfied."""
        return all([
            self.close_below_lower_bb,
            self.rsi_oversold,
            self.adx_below_threshold,
            self.volume_spike,
            self.hourly_rsi_ok,
            self.hourly_close_above_ema,
            self.session_filter_pass,
        ])


class BearGuardConditions(BaseModel):
    """
    Conditions checklist for BearGuard strategy.

    Used for debugging and UI display to show which conditions are met.
    """
    death_cross: bool = False
    close_below_ema_fast: bool = False
    adx_above_threshold: bool = False
    volume_above_average: bool = False
    hourly_ema_falling: bool = False
    hourly_rsi_bearish: bool = False
    session_filter_pass: bool = False

    @property
    def all_short_conditions_met(self) -> bool:
        """Check if all SHORT conditions are satisfied."""
        return all([
            self.death_cross,
            self.close_below_ema_fast,
            self.adx_above_threshold,
            self.volume_above_average,
            self.hourly_ema_falling,
            self.hourly_rsi_bearish,
            self.session_filter_pass,
        ])


class StrategyStateResponse(BaseModel):
    """
    API response for a strategy state record.

    Wraps ``StrategyStateRecord`` for JSON serialisation.
    """
    symbol: str
    strategy: str
    state: StrategyState
    cooldown_until: Optional[datetime] = None
    consecutive_buy_candles: int = 0
    last_exit_time: Optional[datetime] = None
    state_data: Optional[Dict[str, Any]] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(
        json_encoders={
            datetime: lambda v: v.isoformat(),
        }
    )


class StrategySignalSnapshot(BaseModel):
    """
    Derived signal snapshot for a symbol/strategy pair.

    ``signal`` is derived from the current state column.
    ``conditions`` is the raw ``state_data`` JSONB (populated by
    task 3.8 when state persistence is implemented).
    """
    symbol: str
    strategy: str
    state: StrategyState
    signal: Signal
    conditions: Optional[Dict[str, Any]] = None
    updated_at: datetime

    model_config = ConfigDict(
        json_encoders={
            datetime: lambda v: v.isoformat(),
        }
    )


class BacktestMetrics(BaseModel):
    """
    Backtest results and metrics.
    
    Comprehensive statistics for strategy performance evaluation.
    """
    run_id: str
    strategy: str
    symbol: str
    start_date: datetime
    end_date: datetime
    initial_capital: Decimal
    final_capital: Decimal
    total_return: Decimal  # Percentage
    total_trades: int
    winning_trades: int
    losing_trades: int
    win_rate: Decimal  # Percentage
    avg_win: Decimal
    avg_loss: Decimal
    max_drawdown: Decimal  # Percentage
    sharpe_ratio: Optional[Decimal] = None
    profit_factor: Optional[Decimal] = None  # Gross profit / Gross loss
    avg_trade_duration_minutes: Optional[int] = None
    max_consecutive_wins: Optional[int] = None
    max_consecutive_losses: Optional[int] = None
    buy_hold_return: Optional[Decimal] = None
    buy_hold_vs_strategy: Optional[Decimal] = None
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class PortfolioSnapshot(BaseModel):
    """
    Point-in-time portfolio snapshot for equity curve.
    
    Used to track portfolio performance over time.
    """
    timestamp: datetime
    usdt_balance: Decimal
    positions_value: Decimal
    total_equity: Decimal
    daily_pnl: Optional[Decimal] = None
    total_pnl: Decimal = Decimal("0")
    open_positions_count: int = 0
    
    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


class ExitConditionStatus(BaseModel):
    """Status of a single exit condition (met or not)."""
    name: str
    met: bool
    current_value: Optional[str] = None
    threshold: Optional[str] = None


class ExitProximityResponse(BaseModel):
    """How close each exit trigger is to firing for an open position."""
    symbol: str
    strategy: str
    hard_stop_pct: float
    trailing_stop_pct: float
    time_stop_pct: Optional[float] = None
    exit_conditions: List[ExitConditionStatus] = Field(default_factory=list)


class BacktestResult(BaseModel):
    """
    Raw output of a single backtest run.

    Carries the final portfolio state, closed trades, and the
    candle-by-candle equity curve.  ``BacktestMetrics`` is computed
    *from* this result via ``compute_metrics()``.
    """
    strategy_name: str
    symbol: str
    timeframe: str
    start_time: datetime
    end_time: datetime
    candles_processed: int
    portfolio: 'Portfolio'
    trades: List['Trade'] = Field(default_factory=list)
    equity_curve: List['PortfolioSnapshot'] = Field(default_factory=list)
    benchmark_first_price: Optional[Decimal] = None
    benchmark_last_price: Optional[Decimal] = None

    model_config = ConfigDict(
        json_encoders={
            Decimal: lambda v: str(v),
            datetime: lambda v: v.isoformat(),
        }
    )


# ── Exports ──────────────────────────────────────────────────────────────────

__all__ = [
    "Signal",
    "PositionSide",
    "StrategyState",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "ExitReason",
    "RiskAction",
    "RiskDecision",
    "StopCheckResult",
    "Candle",
    "MarketData",
    "Position",
    "Trade",
    "Order",
    "ExecutionResult",
    "Portfolio",
    "StrategyConditions",
    "MeanReversionConditions",
    "BearGuardConditions",
    "StrategyStateResponse",
    "StrategySignalSnapshot",
    "BacktestMetrics",
    "BacktestResult",
    "PortfolioSnapshot",
    "TimeInForce",
]
